# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_bar_1 = QtWidgets.QWidget(self.centralwidget)
        self.side_bar_1.setMinimumSize(QtCore.QSize(175, 0))
        self.side_bar_1.setMaximumSize(QtCore.QSize(175, 16777215))
        self.side_bar_1.setObjectName("side_bar_1")
        self.side_bar_1_verticalLayout = QtWidgets.QVBoxLayout(self.side_bar_1)
        self.side_bar_1_verticalLayout.setObjectName("side_bar_1_verticalLayout")
        self.horizontalLayout.addWidget(self.side_bar_1)
        self.side_bar_2 = QtWidgets.QWidget(self.centralwidget)
        self.side_bar_2.setMinimumSize(QtCore.QSize(175, 0))
        self.side_bar_2.setMaximumSize(QtCore.QSize(175, 16777215))
        self.side_bar_2.setObjectName("side_bar_2")
        self.side_bar_2_verticalLayout = QtWidgets.QVBoxLayout(self.side_bar_2)
        self.side_bar_2_verticalLayout.setObjectName("side_bar_2_verticalLayout")
        self.horizontalLayout.addWidget(self.side_bar_2)
        self.editor_2 = QtWidgets.QWidget(self.centralwidget)
        self.editor_2.setObjectName("editor_2")
        self.editor = QtWidgets.QVBoxLayout(self.editor_2)
        self.editor.setObjectName("editor")
        self.label = QtWidgets.QLabel(self.editor_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.editor.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.editor_2)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setObjectName("textEdit")
        self.editor.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.editor_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDeath_Note = QtWidgets.QMenu(self.menubar)
        self.menuDeath_Note.setObjectName("menuDeath_Note")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Note = QtWidgets.QAction(MainWindow)
        self.actionNew_Note.setObjectName("actionNew_Note")
        self.actionOpen_Note = QtWidgets.QAction(MainWindow)
        self.actionOpen_Note.setObjectName("actionOpen_Note")
        self.actionNew_Directory = QtWidgets.QAction(MainWindow)
        self.actionNew_Directory.setObjectName("actionNew_Directory")
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDeath_Note_Hak_nda = QtWidgets.QAction(MainWindow)
        self.actionDeath_Note_Hak_nda.setObjectName("actionDeath_Note_Hak_nda")
        self.actionTercihler = QtWidgets.QAction(MainWindow)
        self.actionTercihler.setObjectName("actionTercihler")
        self.actionUygulamadan_k = QtWidgets.QAction(MainWindow)
        self.actionUygulamadan_k.setObjectName("actionUygulamadan_k")
        self.menuFile.addAction(self.actionNew_Note)
        self.menuFile.addAction(self.actionOpen_Note)
        self.menuFile.addAction(self.actionNew_Directory)
        self.menuFile.addAction(self.actionOpen_Directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuDeath_Note.addAction(self.actionDeath_Note_Hak_nda)
        self.menuDeath_Note.addAction(self.actionTercihler)
        self.menuDeath_Note.addSeparator()
        self.menuDeath_Note.addAction(self.actionUygulamadan_k)
        self.menubar.addAction(self.menuDeath_Note.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "asdadasd"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDeath_Note.setTitle(_translate("MainWindow", "Death Note"))
        self.actionNew_Note.setText(_translate("MainWindow", "Yeni Not"))
        self.actionOpen_Note.setText(_translate("MainWindow", "Not Aç"))
        self.actionNew_Directory.setText(_translate("MainWindow", "Yeni Klasör"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Klasör Aç"))
        self.actionExit.setText(_translate("MainWindow", "Kaydet"))
        self.actionDeath_Note_Hak_nda.setText(_translate("MainWindow", "Death Note Hakında"))
        self.actionTercihler.setText(_translate("MainWindow", "Tercihler"))
        self.actionUygulamadan_k.setText(_translate("MainWindow", "Uygulamadan Çık"))

